version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_flow_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - user_flow_network
    depends_on:
      - redis
    env_file:
      - .env

  webserver:
    image: nginx:alpine
    container_name: user_flow_webserver
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - user_flow_network

  redis:
    image: redis:alpine
    container_name: user_flow_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - user_flow_network

volumes:
  redis_data:
    driver: local

networks:
  user_flow_network:
    driver: bridge
